# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pip'
    directory: '/requirements'
    schedule:
      interval: 'daily'
    groups:
      # torchvision pins torch, must update in unison
      torch:
        patterns:
          - 'torch'
          - 'torchvision'
    ignore:
      # setuptools releases new versions almost daily
      - dependency-name: 'setuptools'
        update-types: ['version-update:semver-patch']
      # segmentation-models-pytorch pins timm, must update in unison
      - dependency-name: 'timm'