model:
  class_path: BaseModel
  init_args:
    model:
      class_path: lightning_uq_box.models.MLP
      init_args:
        n_inputs: 1
        n_outputs: 1
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
  loss_fn:
    class_path: torch.nn.MSELoss