name: style
on:
  push:
    branches:
    - main
    - release**
  pull_request:
    branches:
    - main
    - release**
defaults:
  run:
    shell: bash

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v7
    - name: Set up uv
      uses: astral-sh/setup-uv@v10.0.1
      with:
        python-version: '3.12'
        enable-cache: true
        prune-cache: true
        activate-environment: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock
    - name: Install dependencies
      run: uv sync --locked --extra style
    - name: List dependencies
      run: uv tree
    - name: Run ruff checks
      run: |
        ruff check --output-format=github --no-fix .
        ruff format --diff
  ty:
    name: ty
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v7
    - name: Set up uv
      uses: astral-sh/setup-uv@v10.0.1
      with:
        python-version: '3.12'
        enable-cache: true
        prune-cache: true
        activate-environment: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock
    - name: Install dependencies
      run: uv sync --locked --extra style --extra tests
    - name: List dependencies
      run: uv tree
    - name: Run ty checks
      run: ty check --output-format=github

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
